### ISSUE TITLE
Allow usage as a profiling/coverage helper?

### ISSUE THREAD

**Issue by johnsonjh** [tmatis/funcheck#100]
Hello,

We're happily using this tool as part of the CI toolchain for a project (https://github.com/aremmell/libsir).  See also https://gitlab.com/libsir/libsir/-/jobs/5570746818 ...

What would be great is some kind of hook to run an external command for each iteration, or some other way help automating the collection of profiling and/or coverage data.

We're doing this now in an ad-hoc way currently, "breaking" certain functions via LD_PRELOAD - see https://github.com/aremmell/libsir/blob/master/.coveralls.sh

We're currently at 95+% coverage (https://coveralls.io/github/aremmell/libsir) but it would be nice to eliminate my custom script and probably raise the coverage numbers as well.

**Comment by tmatis** [comment]
Hello,

Thank you for sharing your positive experience with using funcheck in your CI toolchain for the libsir I appreciate your suggestion for a hook to run external commands and would be happy to explore this further. Could you provide more details or an example of how you envision the implementation? (Command options etc.. ) This will help me better understand your needs and work towards a solution that suits your workflow.

Best regards,
Theo Matis

**Comment by tmatis** [comment]
I'll look tomorrow at your implementation to have a better understanding of your needs

**Comment by tmatis** [comment]
Closed due to inactivity
