### ISSUE TITLE
Wrong count on number of test

### ISSUE THREAD

**Issue by RoyaLProg** [tmatis/funcheck#104]
**Describe the bug**
By the input, there is more test failed that there is tests causing somewhere a long unsigned int overflow

**To Reproduce**

Download tar.gz archive, make, run `funcheck ./rush-02 "10000"`

**Expected behavior**
in this case a 0% success rate, and equal amount of test failed/passed and tests

**Screenshot**

![image](https://github.com/tmatis/funcheck/assets/63088010/6cefdae6-b5cc-4e38-9299-a6ca6acc121d)

**Additional context**
cc -v :
```text
Ubuntu clang version 12.0.1-19ubuntu3
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/10
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/11
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/12
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/10
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/11
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/12
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/12
Candidate multilib: .;@m64
Selected multilib: .;@m64
```
[projects.tar.gz](https://github.com/tmatis/funcheck/files/14853551/projects.tar.gz)

**Comment by tmatis** [comment]
Hello,

thank for reporting this issue i will look into this soon !

Kindest regards,

Froz
